# fly.toml app configuration file generated for tintoria on 2025-04-03T11:53:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tintoria'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  size = 'shared-cpu-1x'
